// Generated by Wrangler on Fri Apr 12 2024 11:04:11 GMT-0300 (Horário Padrão de Brasília)
// by running `wrangler types`

interface Env {
	ENVIRONMENT: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	AWS_REGION: string;
	AWS_DYNAMO_TABLE: string;
}
